version: "3.9"
services:
  db:
    container_name: "hinggu-order-db"
    image: mysql:8.0.28
    platform: linux/amd64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hinggu-order
      MYSQL_USER: order
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d

  application:
    build:
      context: ../
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: "hinggu-order-application"
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - db
